//show all referenced objects from a query

//https://blog.crossjoin.co.uk/2024/10/20/finding-the-columns-touched-by-a-dax-query/

//just replace the Source_Query with whatever... eg copy query from Performance Analyzer
//and replace " with "" (just within Source_Query)

// the rest of the script is fixed

EVALUATE
VAR Source_Query =
"
DEFINE
	VAR __DS0FilterTable = 
		TREATAS({""Accessories""}, 'ProductCategory_BUDGET_Left'[ProductCategoryName])

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('ProductCategory_BUDGET_Right'[ProductCategoryName])),
			NOT('ProductCategory_BUDGET_Right'[ProductCategoryName] IN {""Components""})
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'ProductCategory2'[ProductCategoryName],
			__DS0FilterTable,
			__DS0FilterTable2,
			""Total_Sales_BUDGET_Left"", 'ProductCategory_BUDGET_Left'[Total Sales BUDGET Left],
			""Total_Sales"", 'All Measures 😀'[Total Sales],
			""v_Total_Sales_FormatString"", IGNORE('All Measures 😀'[_Total Sales FormatString]),
			""v_Total_Sales_BUDGET_Left_FormatString"", IGNORE('ProductCategory_BUDGET_Left'[_Total Sales BUDGET Left FormatString]),
			""Total_Sales_BUDGET_Right"", 'ProductCategory_BUDGET_Right'[Total Sales BUDGET Right],
			""v_Total_Sales_BUDGET_Right_FormatString"", IGNORE('ProductCategory_BUDGET_Right'[_Total Sales BUDGET Right FormatString])
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(1001, __DS0Core, [Total_Sales_BUDGET_Left], 0, 'ProductCategory2'[ProductCategoryName], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[Total_Sales_BUDGET_Left] DESC, 'ProductCategory2'[ProductCategoryName]
"
VAR All_Dependencies =
INFO.CALCDEPENDENCY(
	"QUERY",
	Source_Query
)
RETURN All_Dependencies